version: '3'
networks:
  local:


services:

  chat_server:
    container_name: chat_server
    restart: always
    volumes:
      - ./backend/:/app
    build:
      context: ./backend
      dockerfile: Dockerfile
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "4000:8000"
    env_file:
      - .env
    networks:
      - local
