inference:
  input_path: ../output/codes_0.npy
  # output_path: output/clone.wav
  config_name: firefly_gan_vq
  checkpoint_path: ../checkpoints/fish-speech-1.2-sft/firefly-gan-vq-fsq-4x1024-42hz-generator.pth

generate:
  prompt_text: ["Reference text of the voice."]
  prompt_tokens: ["../output/fake.npy"]
  num_samples: 1
  max_new_tokens: 0
  top_p: 0.7
  repetition_penalty: 1.2
  temperature: 0.7
  checkpoint_path: ../checkpoints/fish-speech-1.2-sft
  compile: True
  seed: 42
  half: False
  iterative_prompt: True
  chunk_length: 100
